import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import "../globals.css";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Node Chat",
  description: "Generated by Harsh Dubey",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ToastContainer autoClose={1000} position="top-center" />
        {children}
      </body>
    </html>
  );
}
